media:
  input: /images
  output: /images

content:
  - name: artigos
    label: Artigos
    type: collection
    path: artigos
    filename: "{slug}.md"

    fields:
      - name: layout
        label: Layout
        type: string
        default: post

      - name: title
        label: Título
        type: string
        required: true

      - name: date
        label: Data
        type: date
        required: true

      - name: permalink
        label: Permalink
        type: string

      - name: tags
        label: Tags
        type: string
        list: true

      - name: excerpt
        label: Resumo
        type: text

      - name: body
        label: Conteúdo
        type: rich-text
