media:
  input: images
  output: /images

content:
  - name: artigos
    label: Artigos
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{slug}.md"

    fields:
      - name: layout
        label: Layout
        type: string
        default: post
        hidden: true

      - name: title
        label: Título
        type: string
        required: true

      - name: date
        label: Data
        type: date
        required: true

      - name: tags
        label: Tags
        type: string
        list: true

      - name: excerpt
        label: Resumo
        type: text
        required: true

      - name: body
        label: Conteúdo
        type: rich-text
        required: true
