media:
  input: assets/images
  output: /assets/images

content:
  - name: artigos
    label: Artigos
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{slug}.md"
    view:
      fields: [title, draft, publish_date, created_at]
      primary: title
      sort: [publish_date, created_at, title]
      default:
        sort: publish_date
        order: desc

    fields:
      - name: layout
        label: Layout
        type: string
        default: post
        hidden: true

      - name: title
        label: Título
        type: string
        required: true

      - name: created_at
        label: Data de criação
        type: date
        hidden: true
        options:
          time: true

      - name: publish_date
        label: Data de publicação
        type: date
        required: true
        options:
          time: true

      - name: draft
        label: Rascunho
        type: boolean
        default: true
        description: Se estiver ativo, o artigo não aparece no site.

      - name: tags
        label: Tags
        type: string
        list: true

      - name: excerpt
        label: Resumo
        type: text
        required: true

      - name: body
        label: Conteúdo
        type: rich-text
        required: true
